# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Назва події')),
                ('slug', models.SlugField(blank=True, default='', max_length=250, unique_for_date='publish')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис події')),
                ('publish', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('event_day', models.DateField(null=True, verbose_name='Дата проведення події')),
                ('event_time', models.TimeField(null=True, verbose_name='Час проведення події')),
                ('location_false', models.CharField(blank=True, default='', max_length=550, null=True, verbose_name='Шаблонна Адреса/Місце проведення')),
                ('location', models.CharField(default='', max_length=550, verbose_name='Адреса/Місце проведення')),
                ('latitude', models.CharField(blank=True, default='', max_length=250, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, default='', max_length=250, verbose_name='longitude')),
                ('contact_number', models.CharField(blank=True, default='', max_length=250, verbose_name='Контактний телефон')),
                ('price', models.CharField(blank=True, default='', max_length=250, verbose_name='Ціна')),
                ('ticket', models.CharField(blank=True, default='', max_length=250, verbose_name='Квитки')),
                ('source', models.CharField(blank=True, default='user', max_length=250, verbose_name='Джерело')),
                ('source_href', models.URLField(blank=True, default='', max_length=250, verbose_name='Посилання на джерело')),
                ('vk_href', models.URLField(blank=True, default='', max_length=250, null=True, verbose_name='Посилання vk')),
                ('fb_href', models.URLField(blank=True, default='', max_length=250, null=True, verbose_name='Посилання fb')),
            ],
            options={
                'verbose_name': 'Подія',
                'ordering': ('-publish',),
                'verbose_name_plural': 'Події',
            },
        ),
        migrations.CreateModel(
            name='Gategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Назва')),
                ('slug', models.SlugField(default='', max_length=250, unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=250, verbose_name='Іконка на карті')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Як називається партнер')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото партнера')),
                ('source_href', models.URLField(blank=True, max_length=250, verbose_name='Посилання на партнера')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнери',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Gategories', verbose_name='Категорія'),
        ),
    ]
